### ISSUE TITLE
Wrong parameter for GenServer inside elixir/e10.py example

### ISSUE THREAD

**Issue by greg-latuszek** [Pyrlang/Pyrlang#46]
First of all, thank you for your effort.
While evaluating your library for Python-Elixir communication I've found a bug inside: https://github.com/Pyrlang/Pyrlang/blob/master/examples/elixir/e10.py

`GenServer` requires `node_name` (string) as parameter:
```python
class GenServer(Process):
    def __init__(self, node_name: str, ...
```
but inside example you are passing node object:
```python
class MyProcess(GenServer):
    def __init__(self, node) -> None:
        GenServer.__init__(self, node,
...
    node = Node(node_name="py@127.0.0.1", cookie="COOKIE", engine=event_engine)
    MyProcess(node)
```
this results in:
```
Traceback (most recent call last):
  File "/home/ute/auto/elixir/Pyrlang/examples/elixir/e10.py", line 52, in <module>
    main()
  File "/home/ute/auto/elixir/Pyrlang/examples/elixir/e10.py", line 46, in main
    MyProcess(node)
  File "/home/ute/auto/elixir/Pyrlang/examples/elixir/e10.py", line 26, in __init__
    accepted_calls=['hello', 'hello_again'])
  File "/home/ute/auto/elixir/Pyrlang/pyrlang/gen_server.py", line 57, in __init__
    super().__init__(node_name=node_name)
  File "/home/ute/auto/elixir/Pyrlang/pyrlang/process.py", line 58, in __init__
    node_obj = Node.all_nodes[node_name]
KeyError: <pyrlang.node.Node object at 0x7fd01f2b3c18>
```

To fix it just change to:
```python
class MyProcess(GenServer):
    def __init__(self, node) -> None:
        GenServer.__init__(self, node_name=node.node_name_,
                           accepted_calls=['hello', 'hello_again'])
```
Regards
   Grzegorz Latuszek

**Comment by kvakvs** [comment]
Added the change, thanks!
