### ISSUE TITLE
Doesn't work on OTP 22 

### ISSUE THREAD

**Issue by AlexKovalevych** [Pyrlang/Pyrlang#49]
Starting erlang node with `iex` and trying to connect to pyrlang node:

```
iex --sname b --cookie 123
iex(b@alex-pc)1> :net_adm.ping(:'c@alex-pc')
:pang

```

Logs from pyrlang:

```
ERL_NODE=c@alex-pc ERL_COOKIE=123 PYRLANG_ENABLE_LOG_FORMAT=1 PYRLANG_LOG_LEVEL=DEBUG python main.py                                                                                                                         1 ↵  17:30:59
2019-06-21 17:31:00,076 [pyrlang] gevent_engine:113: Listening on ('0.0.0.0', 0) (40783)
2019-06-21 17:31:00,076 [pyrlang.dist] distribution:58: Listening for dist connections on port 40783
2019-06-21 17:31:00,076 [pyrlang] epmd:89: Connecting 127.0.0.1:4369
2019-06-21 17:31:00,081 [pyrlang] epmd:100: Socket connected
2019-06-21 17:31:00,081 [pyrlang] epmd:167: sending ALIVE2 req n=c@alex-pc (77) vsn=(5, 5)
2019-06-21 17:31:00,082 [pyrlang] epmd:119: Connected successfully (creation 3)
2019-06-21 17:31:00,082 [pyrlang] process:99: Spawned process <3.0.0 @ c@alex-pc>
2019-06-21 17:31:00,082 [pyrlang] process:99: Spawned process <3.0.1 @ c@alex-pc>
2019-06-21 17:31:00,082 [pyrlang] process:99: Spawned process <3.0.2 @ c@alex-pc>
2019-06-21 17:31:00,082 [root] main:17: Registering process - 'my_process'
2019-06-21 17:31:07,437 [pyrlang] gevent_engine:168: Client ('127.0.0.1', 47601) connected
2019-06-21 17:31:07,448 [pyrlang.dist] in_dist_protocol:76: RECV_NAME: (0, 5) b@alex-pc
2019-06-21 17:31:07,449 [pyrlang.dist] in_dist_protocol:117: Sending challenge (our number is 1732719476) c@alex-pc
2019-06-21 17:31:07,470 [pyrlang.dist] in_dist_protocol:95: challengereply: peer's challenge 1761004289
2019-06-21 17:31:07,471 [pyrlang.dist] base_dist_protocol:380: Connected to b@alex-pc
2019-06-21 17:31:07,471 [pyrlang.dist] in_dist_protocol:111: Incoming established with b@alex-pc
2019-06-21 17:31:07,472 [pyrlang] node:162: Node b@alex-pc connected
2019-06-21 17:31:07,504 [pyrlang] gevent_engine:176: Exception: Traceback (most recent call last):
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/async_support/gevent_engine.py", line 173, in _serve_loop
    _read_loop(proto=proto, sock=sock)
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/async_support/gevent_engine.py", line 206, in _read_loop
    collected1 = proto.on_incoming_data(collected)
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/dist/base_dist_protocol.py", line 154, in on_incoming_data
    if self.on_packet(packet):
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/dist/in_dist_protocol.py", line 50, in on_packet
    return self.on_packet_connected(data)
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/dist/base_dist_protocol.py", line 370, in on_packet_connected
    self.on_passthrough_message(control_term, msg_term)
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/dist/base_dist_protocol.py", line 230, in on_passthrough_message
    ref=ref)
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/node.py", line 440, in monitor_process
    return self._monitor_local_process(origin_pid, target_pid, m_ref)
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/node.py", line 466, in _monitor_local_process
    target_proc.add_monitored_by(pid=origin_pid, ref=ref)
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/pyrlang/process.py", line 237, in add_monitored_by
    self._monitored_by[ref] = pid
  File "/home/alex/Sites/py_dedup/env/lib/python3.7/site-packages/term/reference.py", line 81, in __hash__
    return hash((REF_MARKER, self.node_name_, self.id_, self.creation_))
TypeError: unhashable type: 'list'

2019-06-21 17:31:07,504 [pyrlang] gevent_engine:179: Client ('127.0.0.1', 47601) disconnected
2019-06-21 17:31:07,505 [pyrlang] node:169: Node b@alex-pc disconnected
```

Tried with both asyncio and gevent engines - same error

**Comment by kvakvs** [comment]
Noticed that you are using `--sname` i did not do any support for short names. Try start elixir as `--name b@127.0.0.1` for long name.
How do you start Pyrlang? Are cookies the same?

**Comment by AlexKovalevych** [comment]
Tried full name - same result, but not it fails without error:

```
iex(b@127.0.0.1)6> :net_adm.ping(:'d@127.0.0.1')
:pang
```

```
>  ERL_NODE=d@127.0.0.1 ERL_COOKIE=123 PYRLANG_ENABLE_LOG_FORMAT=1 PYRLANG_LOG_LEVEL=DEBUG python main.py                                          
2019-06-22 15:41:13,129 [pyrlang] gevent_engine:113: Listening on ('0.0.0.0', 0) (39829)
2019-06-22 15:41:13,129 [pyrlang.dist] distribution:58: Listening for dist connections on port 39829
2019-06-22 15:41:13,129 [pyrlang] epmd:89: Connecting 127.0.0.1:4369
2019-06-22 15:41:13,137 [pyrlang] epmd:100: Socket connected
2019-06-22 15:41:13,138 [pyrlang] epmd:167: sending ALIVE2 req n=d@alex-pc (77) vsn=(5, 5)
2019-06-22 15:41:13,138 [pyrlang] epmd:119: Connected successfully (creation 2)
2019-06-22 15:41:13,139 [pyrlang] process:99: Spawned process <2.0.0 @ d@alex-pc>
2019-06-22 15:41:13,139 [pyrlang] process:99: Spawned process <2.0.1 @ d@alex-pc>
2019-06-22 15:41:13,139 [pyrlang] process:99: Spawned process <2.0.2 @ d@alex-pc>
2019-06-22 15:41:13,140 [root] main:17: Registering process - 'my_process'
2019-06-22 15:41:18,868 [pyrlang] gevent_engine:168: Client ('127.0.0.1', 49353) connected
2019-06-22 15:41:18,880 [pyrlang.dist] in_dist_protocol:76: RECV_NAME: (0, 5) b@127.0.0.1
2019-06-22 15:41:18,881 [pyrlang.dist] in_dist_protocol:117: Sending challenge (our number is 11019732) d@alex-pc
2019-06-22 15:41:18,904 [pyrlang] gevent_engine:235: Socket closed
2019-06-22 15:41:18,904 [pyrlang] gevent_engine:179: Client ('127.0.0.1', 49353) disconnected
```

**Comment by kvakvs** [comment]
Pyrlang (on master branch) connects as a hidden node. It will not be displayed in `nodes()`

https://github.com/Pyrlang/Pyrlang/blob/master/pyrlang/dist/distflags.py#L64 this needs to have the flag DFLAG_PUBLISHED (called from here https://github.com/Pyrlang/Pyrlang/blob/master/pyrlang/node.py#L106). You can try modify `Node.node_opts_.dflags_` and add that bit manually, not sure i never tried that.

In new version of Pyrlang it will be an option.

**Comment by AlexKovalevych** [comment]
The pyrlang node appeared among hidden nodes, but whatever i do i can't send any message to it, tried pyrlang tests, same error (example 10):

```
make example10a 
PYTHONPATH=/home/alex/Sites/Pyrlang:/home/alex/Sites/Pyrlang/Term PYRLANG_ENABLE_LOG_FORMAT=1 PYRLANG_LOG_LEVEL=DEBUG python3 examples/elixir/e10.py
2019-06-22 23:40:53,641 [pyrlang] gevent_engine:113: Listening on ('0.0.0.0', 0) (35677)
2019-06-22 23:40:53,641 [pyrlang.dist] distribution:58: Listening for dist connections on port 35677
2019-06-22 23:40:53,641 [pyrlang] epmd:89: Connecting 127.0.0.1:4369
2019-06-22 23:40:53,646 [pyrlang] epmd:100: Socket connected
2019-06-22 23:40:53,646 [pyrlang] epmd:167: sending ALIVE2 req n=py@127.0.0.1 (77) vsn=(5, 5)
2019-06-22 23:40:53,647 [pyrlang] epmd:119: Connected successfully (creation 1)
2019-06-22 23:40:53,647 [pyrlang] process:99: Spawned process <1.0.0 @ py@127.0.0.1>
2019-06-22 23:40:53,647 [pyrlang] process:99: Spawned process <1.0.1 @ py@127.0.0.1>
2019-06-22 23:40:53,648 [pyrlang] process:99: Spawned process <1.0.2 @ py@127.0.0.1>
2019-06-22 23:40:53,648 [+++EXAMPLE10+++] e10:27: registering process - 'my_process'
2019-06-22 23:40:56,844 [pyrlang] gevent_engine:168: Client ('127.0.0.1', 52381) connected
2019-06-22 23:40:56,855 [pyrlang.dist] in_dist_protocol:76: RECV_NAME: (0, 5) elixir@127.0.0.1
2019-06-22 23:40:56,855 [pyrlang.dist] in_dist_protocol:117: Sending challenge (our number is 2121747144) py@127.0.0.1
2019-06-22 23:40:56,877 [pyrlang.dist] in_dist_protocol:95: challengereply: peer's challenge 2825423876
2019-06-22 23:40:56,877 [pyrlang.dist] base_dist_protocol:380: Connected to elixir@127.0.0.1
2019-06-22 23:40:56,878 [pyrlang.dist] in_dist_protocol:111: Incoming established with elixir@127.0.0.1
2019-06-22 23:40:56,886 [pyrlang] node:162: Node elixir@127.0.0.1 connected
2019-06-22 23:40:56,902 [pyrlang] gevent_engine:176: Exception: Traceback (most recent call last):
  File "/home/alex/Sites/Pyrlang/pyrlang/async_support/gevent_engine.py", line 173, in _serve_loop
    _read_loop(proto=proto, sock=sock)
  File "/home/alex/Sites/Pyrlang/pyrlang/async_support/gevent_engine.py", line 206, in _read_loop
    collected1 = proto.on_incoming_data(collected)
  File "/home/alex/Sites/Pyrlang/pyrlang/dist/base_dist_protocol.py", line 154, in on_incoming_data
    if self.on_packet(packet):
  File "/home/alex/Sites/Pyrlang/pyrlang/dist/in_dist_protocol.py", line 50, in on_packet
    return self.on_packet_connected(data)
  File "/home/alex/Sites/Pyrlang/pyrlang/dist/base_dist_protocol.py", line 370, in on_packet_connected
    self.on_passthrough_message(control_term, msg_term)
  File "/home/alex/Sites/Pyrlang/pyrlang/dist/base_dist_protocol.py", line 230, in on_passthrough_message
    ref=ref)
  File "/home/alex/Sites/Pyrlang/pyrlang/node.py", line 440, in monitor_process
    return self._monitor_local_process(origin_pid, target_pid, m_ref)
  File "/home/alex/Sites/Pyrlang/pyrlang/node.py", line 466, in _monitor_local_process
    target_proc.add_monitored_by(pid=origin_pid, ref=ref)
  File "/home/alex/Sites/Pyrlang/pyrlang/process.py", line 237, in add_monitored_by
    self._monitored_by[ref] = pid
  File "/home/alex/Sites/Pyrlang/env/lib/python3.7/site-packages/term/reference.py", line 81, in __hash__
    return hash((REF_MARKER, self.node_name_, self.id_, self.creation_))
TypeError: unhashable type: 'list'

2019-06-22 23:40:56,902 [pyrlang] gevent_engine:179: Client ('127.0.0.1', 52381) disconnected
2019-06-22 23:40:56,908 [pyrlang] node:169: Node elixir@127.0.0.1 disconnected
```

```
make example10b                                                                                                                                
elixir --name elixir@127.0.0.1 --cookie COOKIE \
        examples/elixir/e10.exs
warning: found quoted atom "my_process" but the quotes are not required. Atoms made exclusively of Unicode letters, numbers, underscore, and @ do not require quotes
  examples/elixir/e10.exs:13

Test10 trying to connect to py@127.0.0.1 and send some hellos
Calling my_process via a tuple with hello
** (exit) exited in: GenServer.call({:my_process, :"py@127.0.0.1"}, "hello", 5000)
    ** (EXIT) no connection to py@127.0.0.1
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    examples/elixir/e10.exs:15: (file)
    (elixir) lib/code.ex:767: Code.require_file/2
make: *** [Makefile:58: example10b] Error 1
```

**Comment by kvakvs** [comment]
This is a bug in Rust Term library, i will get back to you with the solution asap.
Thanks for the report.

**Comment by AlexKovalevych** [comment]
It works, thank you!
