### ISSUE TITLE
Atom.text_ not implemented

### ISSUE THREAD

**Issue by JamesDBowen** [Pyrlang/Pyrlang#51]
So, I'm not sure if this is an issue with my particular environment, which seems likely, but when attempting to use gen_server.call from elixir to invoke a procedure in Python, I got the following error:

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/async_support/gevent_engine.py", line 206, in _read_loop
    collected1 = proto.on_incoming_data(collected)
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/dist/base_dist_protocol.py", line 154, in on_incoming_data
    if self.on_packet(packet):
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/dist/out_dist_protocol.py", line 50, in on_packet
    return self.on_packet_connected(data)
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/dist/base_dist_protocol.py", line 370, in on_packet_connected
    self.on_passthrough_message(control_term, msg_term)
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/dist/base_dist_protocol.py", line 209, in on_passthrough_message
    message=msg_term)
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/node.py", line 305, in send
    return self._send_local_registered(receiver, message)
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/node.py", line 248, in _send_local_registered
    receiver_obj.deliver_message(msg=message)
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/process.py", line 148, in deliver_message
    self.handle_one_inbox_message(msg)
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/rex.py", line 59, in handle_one_inbox_message
    gencall = gen.parse_gen_call(msg, node_name=self.node_name_)
  File "/Users/claytoncrockett/Documents/Podium/pyrlang_test/Pyrlang/pyrlang/gen.py", line 127, in parse_gen_call
    if not isinstance(msg[0], Atom) or msg[0].text_ != '$gen_call':
AttributeError: 'Atom' object has no attribute 'text_'
```
The relevant line of code is this:
```
    if not isinstance(msg[0], Atom) or msg[0].text_ != '$gen_call':
```

Changing it to:
```
    if not isinstance(msg[0], Atom) or str(msg[0]) != '$gen_call':
```

works flawlessly.  I intend to submit a PR around this, but I'm wondering if this is likely to cause issues for others who are using this library.

**Comment by kvakvs** [comment]
Calling @s2hc-johan to have a look at this, you've changed Atoms recently.
Maybe text_ should become private and encourage users to use `str()` everywhere?

**Comment by s2hc-johan** [comment]
Sorry, thats my bad. I’ll try to fix it tonight.

/J

**Comment by JamesDBowen** [comment]
While we're at it, would you be okay with updating the requirements.txt file to use fixed version numbers for the dependencies instead of >=?  We're intending to use this project in our production environment, and having open-ended dependency versions has the potential to result in breakages like this upon new deployments.
